name: 'olympics_dbt'
version: '1.0.0'
config-version: 2

profile: 'olympics_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olympics_dbt:
    staging:
      materialized: view
    marts:
      core:
        materialized: table
      analysis:
        materialized: table
